### ISSUE TITLE
Estimate time to convert calibration scripts

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/emodpy-snt#10]
* example_nga/simulation/calibration/seasonality_calibration: scripts 01_ - 02_ (two total)
* example_nga/simulation/calibration/baseline_calibration: scripts 01_ - 03_ (three total)
* simulation/calibration/helpers_seasonality_calibration.py
* simulation/calibration/SeasonalityCalibSite.py

**Comment by ZDu-IDM** [comment]
This was completed.
