### ISSUE TITLE
Convert Ben's HBHI Library

### ISSUE THREAD

**Issue by ZDu-IDM** [InstituteforDiseaseModeling/emodpy-snt#27]
Convert hbhi library.
https://github.com/InstituteforDiseaseModeling/emodpy-snt/tree/main/snt/hbhi

**Note**: 
- no need to convert: params_sample.py
- cb_basics.py is simple
- utils.py is simple
- set_up_general.py is similar to helpers_sim_setup.py
- set_up_interventions.py is similar to helpers_add_interventions.py

**Comment by stitova-idm** [comment]
Implemented and tested.
