### ISSUE TITLE
DRUGS: what to do about drug parameter discreptancy

### ISSUE THREAD

**Issue by stitova-idm** [InstituteforDiseaseModeling/emodpy-snt#38]
The default drug parameters are different in  emodpy-malaria and in the files that I'm seeing in Monique's and Ben's files. 
What to do? 
 Options: 1. define Monique's and Ben's drugs that are used "Sulfadoxine", "Pyrimethamine", 'Amodiaquine', SulfadoxinePyrimethamine explicitly as part of "setting up the sims"
2. add them to the default drug parameters as "Sulfadoxine1" or "nu_Sulfadoxine" and call those instead.

**Comment by stitova-idm** [comment]
For now, I am going to explicitly overwrite drug parameters for the projects as needed. I'm also working on a function that sets up the entire drug parameter (so you don't have to do it one parameter at a time)

**Comment by ZDu-IDM** [comment]
This was done.
