### ISSUE TITLE
Estimate time required to convert simulation utils

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/emodpy-snt#8]
* simulation/helpers_add_interventions
* simulation/helpers_sim_setup

Define estimate to convert the following files to emodpy. I output should include a list of issues broken into easy to manage components.

**Comment by stitova-idm** [comment]
I'm done with the first pass (took about a week, but with other work). I need some help from Sharon/Zhaowei and have some questions for the researchers and I think it can be wrapped up in a couple of more days and be ready for testing. Helpers_sim_setup has the most unfinished stuff while helpers_add_interventions is finished, but has comments/questions

**Comment by stitova-idm** [comment]
there was also a add_vaccdrug_campaigns.py that needed to be converted as it's being used you helpers_add_interventions, it also has some comments/questions.

**Comment by stitova-idm** [comment]
PR: https://github.com/InstituteforDiseaseModeling/emodpy-snt/pull/21
