### ISSUE TITLE
Estimate time to convert analyzers

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/emodpy-snt#9]
* example_nga/analyzers/run_analyzers_ssmt.py
* simulation/analyzers/ analyze_helpers.py 
* simulation/analyzers/ analyze_vector_numbers.py
* simulation/analyzers/analyze_monthly_pfpr_u5.py

Calibration analyzers
* simulation/calibration/ChannelByMultiYearSeasonCohortInsetAnalyzer.py

Define estimate to convert the following files to emodpy/idmtools. I output should include a list of issues broken into easy to manage components.

**Comment by ZDu-IDM** [comment]
Implemented #28  in PR:  https://github.com/InstituteforDiseaseModeling/emodpy-snt/pull/28

Calibration related scripts are open.

**Comment by ZDu-IDM** [comment]
This was completed.
